import { SourceMetadata } from './types';

export const MOCK_SOURCES: SourceMetadata[] = [
  {
    id: '1',
    title: 'Community Assessment: Flooding Impact in Mozambique Districts',
    url: 'https://example.org/community-assessment-mozambique',
    sourceType: 'Field Report',
    publishDate: '2026-03-15',
    namedOfficials: [
      { name: 'João Macuiane', role: 'District Administrator, Buzi', context: 'Coordinating local response efforts' },
      { name: 'Maria Santos', role: 'INGD Director', context: 'National disaster management oversight' },
    ],
    namedOrganizations: ['INGD', 'Red Cross Mozambique', 'World Vision'],
    commitments: [
      { actor: 'World Vision', commitment: 'Emergency shelter kits', amount: '5,000 units', timeline: 'Within 2 weeks' },
      { actor: 'INGD', commitment: 'Relocation assistance', amount: null, timeline: 'April 2026' },
    ],
    unmetNeeds: [
      'Safe drinking water for 12,000 displaced families',
      'Medical supplies for health posts in Buzi and Nhamatanda',
      'Emergency communications equipment',
    ],
    geographicSpecificity: 'district',
    sourceLanguage: 'Portuguese',
    citedSources: ['UNICEF Situation Report', 'Local government assessments'],
    eventSpecificity: 0.92,
    actionability: 0.88,
    accountabilitySignal: 0.76,
    communityProximity: 0.94,
    independence: 0.82,
    coverageTopics: ['response', 'commitments', 'gaps', 'accountability'],
    scores: {
      default: 0.86,
      accountability: 0.84,
      community: 0.89,
      climate: 0.87,
      actionable: 0.87,
    },
  },
  {
    id: '2',
    title: 'Climate Attribution Study: Cyclone Freddy Intensity Analysis',
    url: 'https://example.org/climate-attribution-freddy',
    sourceType: 'Research Paper',
    publishDate: '2026-04-01',
    namedOfficials: [],
    namedOrganizations: ['World Weather Attribution', 'Imperial College London', 'KNMI'],
    commitments: [],
    unmetNeeds: [],
    geographicSpecificity: 'regional',
    sourceLanguage: 'English',
    citedSources: ['CMIP6 climate models', 'IMD meteorological data', 'EM-DAT disaster database'],
    eventSpecificity: 0.85,
    actionability: 0.45,
    accountabilitySignal: 0.38,
    communityProximity: 0.22,
    independence: 0.95,
    coverageTopics: ['causes', 'overview'],
    scores: {
      default: 0.57,
      accountability: 0.55,
      community: 0.51,
      climate: 0.73,
      actionable: 0.55,
    },
  },
  {
    id: '3',
    title: 'UN OCHA Mozambique: Cyclone Response Situation Report #4',
    url: 'https://example.org/ocha-sitrep-4',
    sourceType: 'Situation Report',
    publishDate: '2026-03-20',
    namedOfficials: [
      { name: 'Manuel Chang', role: 'Humanitarian Coordinator', context: 'Leading UN response coordination' },
    ],
    namedOrganizations: ['OCHA', 'WFP', 'UNICEF', 'IOM', 'UNDP'],
    commitments: [
      { actor: 'WFP', commitment: 'Food assistance', amount: '$12 million', timeline: 'March-June 2026' },
      { actor: 'UNICEF', commitment: 'WASH services', amount: '$8 million', timeline: 'Ongoing' },
    ],
    unmetNeeds: [
      'Funding gap of $45 million for full response',
      'Logistics capacity for remote areas',
    ],
    geographicSpecificity: 'national',
    sourceLanguage: 'English',
    citedSources: ['Government of Mozambique', 'Cluster reports'],
    eventSpecificity: 0.78,
    actionability: 0.72,
    accountabilitySignal: 0.65,
    communityProximity: 0.48,
    independence: 0.58,
    coverageTopics: ['overview', 'response', 'commitments', 'gaps'],
    scores: {
      default: 0.68,
      accountability: 0.65,
      community: 0.67,
      climate: 0.65,
      actionable: 0.70,
    },
  },
  {
    id: '4',
    title: 'Firsthand Account: Voices from Beira Shelters',
    url: 'https://example.org/beira-testimonies',
    sourceType: 'Community Report',
    publishDate: '2026-03-18',
    namedOfficials: [],
    namedOrganizations: ['Local Community Network', 'Caritas Mozambique'],
    commitments: [],
    unmetNeeds: [
      'Children unable to attend school due to damaged buildings',
      'Lack of privacy and dignity in temporary shelters',
      'No access to livelihood restoration programs',
      'Mental health support services needed',
    ],
    geographicSpecificity: 'district',
    sourceLanguage: 'Portuguese',
    citedSources: [],
    eventSpecificity: 0.96,
    actionability: 0.82,
    accountabilitySignal: 0.71,
    communityProximity: 0.98,
    independence: 0.88,
    coverageTopics: ['gaps', 'response', 'recovery'],
    scores: {
      default: 0.87,
      accountability: 0.82,
      community: 0.92,
      climate: 0.89,
      actionable: 0.86,
    },
  },
  {
    id: '5',
    title: 'Government Press Release: National Recovery Framework',
    url: 'https://example.org/govt-recovery-framework',
    sourceType: 'Official Statement',
    publishDate: '2026-03-25',
    namedOfficials: [
      { name: 'Filipe Nyusi', role: 'President of Mozambique', context: 'Announcing national recovery plan' },
      { name: 'Arsenio Mabote', role: 'Minister of Public Works', context: 'Infrastructure rebuilding commitments' },
    ],
    namedOrganizations: ['Government of Mozambique', 'World Bank', 'African Development Bank'],
    commitments: [
      { actor: 'Government of Mozambique', commitment: 'Infrastructure reconstruction', amount: '$200 million', timeline: '2026-2028' },
      { actor: 'World Bank', commitment: 'Recovery loan', amount: '$150 million', timeline: 'Approved April 2026' },
    ],
    unmetNeeds: [],
    geographicSpecificity: 'national',
    sourceLanguage: 'Portuguese',
    citedSources: ['World Bank assessments', 'Post-Disaster Needs Assessment'],
    eventSpecificity: 0.72,
    actionability: 0.68,
    accountabilitySignal: 0.52,
    communityProximity: 0.28,
    independence: 0.15,
    coverageTopics: ['commitments', 'preparedness', 'recovery'],
    scores: {
      default: 0.52,
      accountability: 0.45,
      community: 0.55,
      climate: 0.51,
      actionable: 0.60,
    },
  },
  {
    id: '6',
    title: 'Early Warning Systems Gap Analysis for Southern Africa',
    url: 'https://example.org/ews-gap-analysis',
    sourceType: 'Technical Report',
    publishDate: '2026-03-10',
    namedOfficials: [],
    namedOrganizations: ['WMO', 'SADC Climate Services Centre', 'CREWS Initiative'],
    commitments: [
      { actor: 'CREWS Initiative', commitment: 'Early warning system enhancement', amount: '$25 million', timeline: '2026-2030' },
    ],
    unmetNeeds: [
      'Last-mile communication infrastructure in rural areas',
      'Community-based early action protocols',
    ],
    geographicSpecificity: 'regional',
    sourceLanguage: 'English',
    citedSources: ['WMO guidelines', 'National meteorological services data'],
    eventSpecificity: 0.58,
    actionability: 0.76,
    accountabilitySignal: 0.62,
    communityProximity: 0.42,
    independence: 0.78,
    coverageTopics: ['preparedness', 'gaps', 'accountability'],
    scores: {
      default: 0.64,
      accountability: 0.66,
      community: 0.67,
      climate: 0.68,
      actionable: 0.69,
    },
  },
];
